#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLTC")]
	public partial class LinQtoSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCT_HANG_MUC_CHI(CT_HANG_MUC_CHI instance);
    partial void UpdateCT_HANG_MUC_CHI(CT_HANG_MUC_CHI instance);
    partial void DeleteCT_HANG_MUC_CHI(CT_HANG_MUC_CHI instance);
    partial void InsertTIEN_TE(TIEN_TE instance);
    partial void UpdateTIEN_TE(TIEN_TE instance);
    partial void DeleteTIEN_TE(TIEN_TE instance);
    partial void InsertDM_MANHINH(DM_MANHINH instance);
    partial void UpdateDM_MANHINH(DM_MANHINH instance);
    partial void DeleteDM_MANHINH(DM_MANHINH instance);
    partial void InsertHANG_MUC_CHI(HANG_MUC_CHI instance);
    partial void UpdateHANG_MUC_CHI(HANG_MUC_CHI instance);
    partial void DeleteHANG_MUC_CHI(HANG_MUC_CHI instance);
    partial void InsertHANG_MUC_THU(HANG_MUC_THU instance);
    partial void UpdateHANG_MUC_THU(HANG_MUC_THU instance);
    partial void DeleteHANG_MUC_THU(HANG_MUC_THU instance);
    partial void InsertPHIEU_CHI(PHIEU_CHI instance);
    partial void UpdatePHIEU_CHI(PHIEU_CHI instance);
    partial void DeletePHIEU_CHI(PHIEU_CHI instance);
    partial void InsertPHIEU_THU(PHIEU_THU instance);
    partial void UpdatePHIEU_THU(PHIEU_THU instance);
    partial void DeletePHIEU_THU(PHIEU_THU instance);
    partial void InsertQL_NGUOI_DUNG(QL_NGUOI_DUNG instance);
    partial void UpdateQL_NGUOI_DUNG(QL_NGUOI_DUNG instance);
    partial void DeleteQL_NGUOI_DUNG(QL_NGUOI_DUNG instance);
    partial void InsertQL_NGUOIDUNG_NHOMNGUOIDUNG(QL_NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void UpdateQL_NGUOIDUNG_NHOMNGUOIDUNG(QL_NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void DeleteQL_NGUOIDUNG_NHOMNGUOIDUNG(QL_NGUOIDUNG_NHOMNGUOIDUNG instance);
    partial void InsertQL_NHOM_ND(QL_NHOM_ND instance);
    partial void UpdateQL_NHOM_ND(QL_NHOM_ND instance);
    partial void DeleteQL_NHOM_ND(QL_NHOM_ND instance);
    partial void InsertQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void UpdateQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void DeleteQL_PHANQUYEN(QL_PHANQUYEN instance);
    partial void InsertTAI_KHOAN(TAI_KHOAN instance);
    partial void UpdateTAI_KHOAN(TAI_KHOAN instance);
    partial void DeleteTAI_KHOAN(TAI_KHOAN instance);
    #endregion
		
		public LinQtoSQLDataContext() : 
				base(global::LinQ.Properties.Settings.Default.QLTCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinQtoSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQtoSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQtoSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinQtoSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CT_HANG_MUC_CHI> CT_HANG_MUC_CHIs
		{
			get
			{
				return this.GetTable<CT_HANG_MUC_CHI>();
			}
		}
		
		public System.Data.Linq.Table<TIEN_TE> TIEN_TEs
		{
			get
			{
				return this.GetTable<TIEN_TE>();
			}
		}
		
		public System.Data.Linq.Table<DM_MANHINH> DM_MANHINHs
		{
			get
			{
				return this.GetTable<DM_MANHINH>();
			}
		}
		
		public System.Data.Linq.Table<HANG_MUC_CHI> HANG_MUC_CHIs
		{
			get
			{
				return this.GetTable<HANG_MUC_CHI>();
			}
		}
		
		public System.Data.Linq.Table<HANG_MUC_THU> HANG_MUC_THUs
		{
			get
			{
				return this.GetTable<HANG_MUC_THU>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_CHI> PHIEU_CHIs
		{
			get
			{
				return this.GetTable<PHIEU_CHI>();
			}
		}
		
		public System.Data.Linq.Table<PHIEU_THU> PHIEU_THUs
		{
			get
			{
				return this.GetTable<PHIEU_THU>();
			}
		}
		
		public System.Data.Linq.Table<QL_NGUOI_DUNG> QL_NGUOI_DUNGs
		{
			get
			{
				return this.GetTable<QL_NGUOI_DUNG>();
			}
		}
		
		public System.Data.Linq.Table<QL_NGUOIDUNG_NHOMNGUOIDUNG> QL_NGUOIDUNG_NHOMNGUOIDUNGs
		{
			get
			{
				return this.GetTable<QL_NGUOIDUNG_NHOMNGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<QL_NHOM_ND> QL_NHOM_NDs
		{
			get
			{
				return this.GetTable<QL_NHOM_ND>();
			}
		}
		
		public System.Data.Linq.Table<QL_PHANQUYEN> QL_PHANQUYENs
		{
			get
			{
				return this.GetTable<QL_PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this.GetTable<TAI_KHOAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CT_HANG_MUC_CHI")]
	public partial class CT_HANG_MUC_CHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_CTHM_CHI;
		
		private string _TEN_CTHM_CHI;
		
		private string _GHI_CHU;
		
		private System.Nullable<int> _MA_HM_CHI;
		
		private EntitySet<PHIEU_CHI> _PHIEU_CHIs;
		
		private EntityRef<HANG_MUC_CHI> _HANG_MUC_CHI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_CTHM_CHIChanging(int value);
    partial void OnMA_CTHM_CHIChanged();
    partial void OnTEN_CTHM_CHIChanging(string value);
    partial void OnTEN_CTHM_CHIChanged();
    partial void OnGHI_CHUChanging(string value);
    partial void OnGHI_CHUChanged();
    partial void OnMA_HM_CHIChanging(System.Nullable<int> value);
    partial void OnMA_HM_CHIChanged();
    #endregion
		
		public CT_HANG_MUC_CHI()
		{
			this._PHIEU_CHIs = new EntitySet<PHIEU_CHI>(new Action<PHIEU_CHI>(this.attach_PHIEU_CHIs), new Action<PHIEU_CHI>(this.detach_PHIEU_CHIs));
			this._HANG_MUC_CHI = default(EntityRef<HANG_MUC_CHI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CTHM_CHI", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_CTHM_CHI
		{
			get
			{
				return this._MA_CTHM_CHI;
			}
			set
			{
				if ((this._MA_CTHM_CHI != value))
				{
					this.OnMA_CTHM_CHIChanging(value);
					this.SendPropertyChanging();
					this._MA_CTHM_CHI = value;
					this.SendPropertyChanged("MA_CTHM_CHI");
					this.OnMA_CTHM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_CTHM_CHI", DbType="NVarChar(30)")]
		public string TEN_CTHM_CHI
		{
			get
			{
				return this._TEN_CTHM_CHI;
			}
			set
			{
				if ((this._TEN_CTHM_CHI != value))
				{
					this.OnTEN_CTHM_CHIChanging(value);
					this.SendPropertyChanging();
					this._TEN_CTHM_CHI = value;
					this.SendPropertyChanged("TEN_CTHM_CHI");
					this.OnTEN_CTHM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHI_CHU", DbType="NVarChar(30)")]
		public string GHI_CHU
		{
			get
			{
				return this._GHI_CHU;
			}
			set
			{
				if ((this._GHI_CHU != value))
				{
					this.OnGHI_CHUChanging(value);
					this.SendPropertyChanging();
					this._GHI_CHU = value;
					this.SendPropertyChanged("GHI_CHU");
					this.OnGHI_CHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HM_CHI", DbType="Int")]
		public System.Nullable<int> MA_HM_CHI
		{
			get
			{
				return this._MA_HM_CHI;
			}
			set
			{
				if ((this._MA_HM_CHI != value))
				{
					if (this._HANG_MUC_CHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HM_CHIChanging(value);
					this.SendPropertyChanging();
					this._MA_HM_CHI = value;
					this.SendPropertyChanged("MA_HM_CHI");
					this.OnMA_HM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CT_HANG_MUC_CHI_PHIEU_CHI", Storage="_PHIEU_CHIs", ThisKey="MA_CTHM_CHI", OtherKey="MA_CTHM_CHI")]
		public EntitySet<PHIEU_CHI> PHIEU_CHIs
		{
			get
			{
				return this._PHIEU_CHIs;
			}
			set
			{
				this._PHIEU_CHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_MUC_CHI_CT_HANG_MUC_CHI", Storage="_HANG_MUC_CHI", ThisKey="MA_HM_CHI", OtherKey="MA_HM_CHI", IsForeignKey=true)]
		public HANG_MUC_CHI HANG_MUC_CHI
		{
			get
			{
				return this._HANG_MUC_CHI.Entity;
			}
			set
			{
				HANG_MUC_CHI previousValue = this._HANG_MUC_CHI.Entity;
				if (((previousValue != value) 
							|| (this._HANG_MUC_CHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANG_MUC_CHI.Entity = null;
						previousValue.CT_HANG_MUC_CHIs.Remove(this);
					}
					this._HANG_MUC_CHI.Entity = value;
					if ((value != null))
					{
						value.CT_HANG_MUC_CHIs.Add(this);
						this._MA_HM_CHI = value.MA_HM_CHI;
					}
					else
					{
						this._MA_HM_CHI = default(Nullable<int>);
					}
					this.SendPropertyChanged("HANG_MUC_CHI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_CHIs(PHIEU_CHI entity)
		{
			this.SendPropertyChanging();
			entity.CT_HANG_MUC_CHI = this;
		}
		
		private void detach_PHIEU_CHIs(PHIEU_CHI entity)
		{
			this.SendPropertyChanging();
			entity.CT_HANG_MUC_CHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TIEN_TE")]
	public partial class TIEN_TE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI;
		
		private string _TENLOAI;
		
		private System.Nullable<decimal> _TI_GIA;
		
		private EntitySet<TAI_KHOAN> _TAI_KHOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    partial void OnTI_GIAChanging(System.Nullable<decimal> value);
    partial void OnTI_GIAChanged();
    #endregion
		
		public TIEN_TE()
		{
			this._TAI_KHOANs = new EntitySet<TAI_KHOAN>(new Action<TAI_KHOAN>(this.attach_TAI_KHOANs), new Action<TAI_KHOAN>(this.detach_TAI_KHOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="Char(5)")]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TI_GIA", DbType="Money")]
		public System.Nullable<decimal> TI_GIA
		{
			get
			{
				return this._TI_GIA;
			}
			set
			{
				if ((this._TI_GIA != value))
				{
					this.OnTI_GIAChanging(value);
					this.SendPropertyChanging();
					this._TI_GIA = value;
					this.SendPropertyChanged("TI_GIA");
					this.OnTI_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIEN_TE_TAI_KHOAN", Storage="_TAI_KHOANs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this._TAI_KHOANs;
			}
			set
			{
				this._TAI_KHOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.TIEN_TE = this;
		}
		
		private void detach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.TIEN_TE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DM_MANHINH")]
	public partial class DM_MANHINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_MANHINH;
		
		private string _TEN_MANHINH;
		
		private EntitySet<QL_PHANQUYEN> _QL_PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_MANHINHChanging(int value);
    partial void OnMA_MANHINHChanged();
    partial void OnTEN_MANHINHChanging(string value);
    partial void OnTEN_MANHINHChanged();
    #endregion
		
		public DM_MANHINH()
		{
			this._QL_PHANQUYENs = new EntitySet<QL_PHANQUYEN>(new Action<QL_PHANQUYEN>(this.attach_QL_PHANQUYENs), new Action<QL_PHANQUYEN>(this.detach_QL_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MANHINH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_MANHINH
		{
			get
			{
				return this._MA_MANHINH;
			}
			set
			{
				if ((this._MA_MANHINH != value))
				{
					this.OnMA_MANHINHChanging(value);
					this.SendPropertyChanging();
					this._MA_MANHINH = value;
					this.SendPropertyChanged("MA_MANHINH");
					this.OnMA_MANHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_MANHINH", DbType="Char(10)")]
		public string TEN_MANHINH
		{
			get
			{
				return this._TEN_MANHINH;
			}
			set
			{
				if ((this._TEN_MANHINH != value))
				{
					this.OnTEN_MANHINHChanging(value);
					this.SendPropertyChanging();
					this._TEN_MANHINH = value;
					this.SendPropertyChanged("TEN_MANHINH");
					this.OnTEN_MANHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_MANHINH_QL_PHANQUYEN", Storage="_QL_PHANQUYENs", ThisKey="MA_MANHINH", OtherKey="MA_MANHINH")]
		public EntitySet<QL_PHANQUYEN> QL_PHANQUYENs
		{
			get
			{
				return this._QL_PHANQUYENs;
			}
			set
			{
				this._QL_PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_PHANQUYENs(QL_PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_MANHINH = this;
		}
		
		private void detach_QL_PHANQUYENs(QL_PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.DM_MANHINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANG_MUC_CHI")]
	public partial class HANG_MUC_CHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HM_CHI;
		
		private string _TEN_HM_CHI;
		
		private string _CHUTHICH;
		
		private EntitySet<CT_HANG_MUC_CHI> _CT_HANG_MUC_CHIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HM_CHIChanging(int value);
    partial void OnMA_HM_CHIChanged();
    partial void OnTEN_HM_CHIChanging(string value);
    partial void OnTEN_HM_CHIChanged();
    partial void OnCHUTHICHChanging(string value);
    partial void OnCHUTHICHChanged();
    #endregion
		
		public HANG_MUC_CHI()
		{
			this._CT_HANG_MUC_CHIs = new EntitySet<CT_HANG_MUC_CHI>(new Action<CT_HANG_MUC_CHI>(this.attach_CT_HANG_MUC_CHIs), new Action<CT_HANG_MUC_CHI>(this.detach_CT_HANG_MUC_CHIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HM_CHI", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_HM_CHI
		{
			get
			{
				return this._MA_HM_CHI;
			}
			set
			{
				if ((this._MA_HM_CHI != value))
				{
					this.OnMA_HM_CHIChanging(value);
					this.SendPropertyChanging();
					this._MA_HM_CHI = value;
					this.SendPropertyChanged("MA_HM_CHI");
					this.OnMA_HM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_HM_CHI", DbType="NVarChar(30)")]
		public string TEN_HM_CHI
		{
			get
			{
				return this._TEN_HM_CHI;
			}
			set
			{
				if ((this._TEN_HM_CHI != value))
				{
					this.OnTEN_HM_CHIChanging(value);
					this.SendPropertyChanging();
					this._TEN_HM_CHI = value;
					this.SendPropertyChanged("TEN_HM_CHI");
					this.OnTEN_HM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUTHICH", DbType="NVarChar(30)")]
		public string CHUTHICH
		{
			get
			{
				return this._CHUTHICH;
			}
			set
			{
				if ((this._CHUTHICH != value))
				{
					this.OnCHUTHICHChanging(value);
					this.SendPropertyChanging();
					this._CHUTHICH = value;
					this.SendPropertyChanged("CHUTHICH");
					this.OnCHUTHICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_MUC_CHI_CT_HANG_MUC_CHI", Storage="_CT_HANG_MUC_CHIs", ThisKey="MA_HM_CHI", OtherKey="MA_HM_CHI")]
		public EntitySet<CT_HANG_MUC_CHI> CT_HANG_MUC_CHIs
		{
			get
			{
				return this._CT_HANG_MUC_CHIs;
			}
			set
			{
				this._CT_HANG_MUC_CHIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CT_HANG_MUC_CHIs(CT_HANG_MUC_CHI entity)
		{
			this.SendPropertyChanging();
			entity.HANG_MUC_CHI = this;
		}
		
		private void detach_CT_HANG_MUC_CHIs(CT_HANG_MUC_CHI entity)
		{
			this.SendPropertyChanging();
			entity.HANG_MUC_CHI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANG_MUC_THU")]
	public partial class HANG_MUC_THU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MA_HM_THU;
		
		private string _TEN_HM_THU;
		
		private string _NOTE;
		
		private EntitySet<PHIEU_THU> _PHIEU_THUs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_HM_THUChanging(int value);
    partial void OnMA_HM_THUChanged();
    partial void OnTEN_HM_THUChanging(string value);
    partial void OnTEN_HM_THUChanged();
    partial void OnNOTEChanging(string value);
    partial void OnNOTEChanged();
    #endregion
		
		public HANG_MUC_THU()
		{
			this._PHIEU_THUs = new EntitySet<PHIEU_THU>(new Action<PHIEU_THU>(this.attach_PHIEU_THUs), new Action<PHIEU_THU>(this.detach_PHIEU_THUs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HM_THU", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_HM_THU
		{
			get
			{
				return this._MA_HM_THU;
			}
			set
			{
				if ((this._MA_HM_THU != value))
				{
					this.OnMA_HM_THUChanging(value);
					this.SendPropertyChanging();
					this._MA_HM_THU = value;
					this.SendPropertyChanged("MA_HM_THU");
					this.OnMA_HM_THUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_HM_THU", DbType="NVarChar(30)")]
		public string TEN_HM_THU
		{
			get
			{
				return this._TEN_HM_THU;
			}
			set
			{
				if ((this._TEN_HM_THU != value))
				{
					this.OnTEN_HM_THUChanging(value);
					this.SendPropertyChanging();
					this._TEN_HM_THU = value;
					this.SendPropertyChanged("TEN_HM_THU");
					this.OnTEN_HM_THUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTE", DbType="VarChar(30)")]
		public string NOTE
		{
			get
			{
				return this._NOTE;
			}
			set
			{
				if ((this._NOTE != value))
				{
					this.OnNOTEChanging(value);
					this.SendPropertyChanging();
					this._NOTE = value;
					this.SendPropertyChanged("NOTE");
					this.OnNOTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_MUC_THU_PHIEU_THU", Storage="_PHIEU_THUs", ThisKey="MA_HM_THU", OtherKey="MA_HM_THU")]
		public EntitySet<PHIEU_THU> PHIEU_THUs
		{
			get
			{
				return this._PHIEU_THUs;
			}
			set
			{
				this._PHIEU_THUs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_THUs(PHIEU_THU entity)
		{
			this.SendPropertyChanging();
			entity.HANG_MUC_THU = this;
		}
		
		private void detach_PHIEU_THUs(PHIEU_THU entity)
		{
			this.SendPropertyChanging();
			entity.HANG_MUC_THU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_CHI")]
	public partial class PHIEU_CHI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_PCHI;
		
		private int _MA_CTHM_CHI;
		
		private string _MATK;
		
		private System.Nullable<System.DateTime> _NGAY_LAP;
		
		private System.Nullable<decimal> _SO_TIEN;
		
		private string _CHU_THICH;
		
		private string _CHI_CHO_AI;
		
		private EntityRef<CT_HANG_MUC_CHI> _CT_HANG_MUC_CHI;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_PCHIChanging(string value);
    partial void OnMA_PCHIChanged();
    partial void OnMA_CTHM_CHIChanging(int value);
    partial void OnMA_CTHM_CHIChanged();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnNGAY_LAPChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAY_LAPChanged();
    partial void OnSO_TIENChanging(System.Nullable<decimal> value);
    partial void OnSO_TIENChanged();
    partial void OnCHU_THICHChanging(string value);
    partial void OnCHU_THICHChanged();
    partial void OnCHI_CHO_AIChanging(string value);
    partial void OnCHI_CHO_AIChanged();
    #endregion
		
		public PHIEU_CHI()
		{
			this._CT_HANG_MUC_CHI = default(EntityRef<CT_HANG_MUC_CHI>);
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_PCHI", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_PCHI
		{
			get
			{
				return this._MA_PCHI;
			}
			set
			{
				if ((this._MA_PCHI != value))
				{
					this.OnMA_PCHIChanging(value);
					this.SendPropertyChanging();
					this._MA_PCHI = value;
					this.SendPropertyChanged("MA_PCHI");
					this.OnMA_PCHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_CTHM_CHI", DbType="Int NOT NULL")]
		public int MA_CTHM_CHI
		{
			get
			{
				return this._MA_CTHM_CHI;
			}
			set
			{
				if ((this._MA_CTHM_CHI != value))
				{
					if (this._CT_HANG_MUC_CHI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_CTHM_CHIChanging(value);
					this.SendPropertyChanging();
					this._MA_CTHM_CHI = value;
					this.SendPropertyChanged("MA_CTHM_CHI");
					this.OnMA_CTHM_CHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_LAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> NGAY_LAP
		{
			get
			{
				return this._NGAY_LAP;
			}
			set
			{
				if ((this._NGAY_LAP != value))
				{
					this.OnNGAY_LAPChanging(value);
					this.SendPropertyChanging();
					this._NGAY_LAP = value;
					this.SendPropertyChanged("NGAY_LAP");
					this.OnNGAY_LAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_TIEN", DbType="Money")]
		public System.Nullable<decimal> SO_TIEN
		{
			get
			{
				return this._SO_TIEN;
			}
			set
			{
				if ((this._SO_TIEN != value))
				{
					this.OnSO_TIENChanging(value);
					this.SendPropertyChanging();
					this._SO_TIEN = value;
					this.SendPropertyChanged("SO_TIEN");
					this.OnSO_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHU_THICH", DbType="NVarChar(30)")]
		public string CHU_THICH
		{
			get
			{
				return this._CHU_THICH;
			}
			set
			{
				if ((this._CHU_THICH != value))
				{
					this.OnCHU_THICHChanging(value);
					this.SendPropertyChanging();
					this._CHU_THICH = value;
					this.SendPropertyChanged("CHU_THICH");
					this.OnCHU_THICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHI_CHO_AI", DbType="NVarChar(50)")]
		public string CHI_CHO_AI
		{
			get
			{
				return this._CHI_CHO_AI;
			}
			set
			{
				if ((this._CHI_CHO_AI != value))
				{
					this.OnCHI_CHO_AIChanging(value);
					this.SendPropertyChanging();
					this._CHI_CHO_AI = value;
					this.SendPropertyChanged("CHI_CHO_AI");
					this.OnCHI_CHO_AIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CT_HANG_MUC_CHI_PHIEU_CHI", Storage="_CT_HANG_MUC_CHI", ThisKey="MA_CTHM_CHI", OtherKey="MA_CTHM_CHI", IsForeignKey=true)]
		public CT_HANG_MUC_CHI CT_HANG_MUC_CHI
		{
			get
			{
				return this._CT_HANG_MUC_CHI.Entity;
			}
			set
			{
				CT_HANG_MUC_CHI previousValue = this._CT_HANG_MUC_CHI.Entity;
				if (((previousValue != value) 
							|| (this._CT_HANG_MUC_CHI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CT_HANG_MUC_CHI.Entity = null;
						previousValue.PHIEU_CHIs.Remove(this);
					}
					this._CT_HANG_MUC_CHI.Entity = value;
					if ((value != null))
					{
						value.PHIEU_CHIs.Add(this);
						this._MA_CTHM_CHI = value.MA_CTHM_CHI;
					}
					else
					{
						this._MA_CTHM_CHI = default(int);
					}
					this.SendPropertyChanged("CT_HANG_MUC_CHI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_PHIEU_CHI", Storage="_TAI_KHOAN", ThisKey="MATK", OtherKey="MATK", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.PHIEU_CHIs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEU_CHIs.Add(this);
						this._MATK = value.MATK;
					}
					else
					{
						this._MATK = default(string);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEU_THU")]
	public partial class PHIEU_THU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPTHU;
		
		private int _MA_HM_THU;
		
		private string _MATK;
		
		private System.Nullable<decimal> _TIEN;
		
		private string _GHICHU;
		
		private string _THU_TU_AI;
		
		private EntityRef<HANG_MUC_THU> _HANG_MUC_THU;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPTHUChanging(string value);
    partial void OnMAPTHUChanged();
    partial void OnMA_HM_THUChanging(int value);
    partial void OnMA_HM_THUChanged();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnTIENChanging(System.Nullable<decimal> value);
    partial void OnTIENChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnTHU_TU_AIChanging(string value);
    partial void OnTHU_TU_AIChanged();
    #endregion
		
		public PHIEU_THU()
		{
			this._HANG_MUC_THU = default(EntityRef<HANG_MUC_THU>);
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPTHU", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPTHU
		{
			get
			{
				return this._MAPTHU;
			}
			set
			{
				if ((this._MAPTHU != value))
				{
					this.OnMAPTHUChanging(value);
					this.SendPropertyChanging();
					this._MAPTHU = value;
					this.SendPropertyChanged("MAPTHU");
					this.OnMAPTHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_HM_THU", DbType="Int NOT NULL")]
		public int MA_HM_THU
		{
			get
			{
				return this._MA_HM_THU;
			}
			set
			{
				if ((this._MA_HM_THU != value))
				{
					if (this._HANG_MUC_THU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_HM_THUChanging(value);
					this.SendPropertyChanging();
					this._MA_HM_THU = value;
					this.SendPropertyChanged("MA_HM_THU");
					this.OnMA_HM_THUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEN", DbType="Money")]
		public System.Nullable<decimal> TIEN
		{
			get
			{
				return this._TIEN;
			}
			set
			{
				if ((this._TIEN != value))
				{
					this.OnTIENChanging(value);
					this.SendPropertyChanging();
					this._TIEN = value;
					this.SendPropertyChanged("TIEN");
					this.OnTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="VarChar(100)")]
		public string GHICHU
		{
			get
			{
				return this._GHICHU;
			}
			set
			{
				if ((this._GHICHU != value))
				{
					this.OnGHICHUChanging(value);
					this.SendPropertyChanging();
					this._GHICHU = value;
					this.SendPropertyChanged("GHICHU");
					this.OnGHICHUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THU_TU_AI", DbType="NVarChar(50)")]
		public string THU_TU_AI
		{
			get
			{
				return this._THU_TU_AI;
			}
			set
			{
				if ((this._THU_TU_AI != value))
				{
					this.OnTHU_TU_AIChanging(value);
					this.SendPropertyChanging();
					this._THU_TU_AI = value;
					this.SendPropertyChanged("THU_TU_AI");
					this.OnTHU_TU_AIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HANG_MUC_THU_PHIEU_THU", Storage="_HANG_MUC_THU", ThisKey="MA_HM_THU", OtherKey="MA_HM_THU", IsForeignKey=true)]
		public HANG_MUC_THU HANG_MUC_THU
		{
			get
			{
				return this._HANG_MUC_THU.Entity;
			}
			set
			{
				HANG_MUC_THU previousValue = this._HANG_MUC_THU.Entity;
				if (((previousValue != value) 
							|| (this._HANG_MUC_THU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HANG_MUC_THU.Entity = null;
						previousValue.PHIEU_THUs.Remove(this);
					}
					this._HANG_MUC_THU.Entity = value;
					if ((value != null))
					{
						value.PHIEU_THUs.Add(this);
						this._MA_HM_THU = value.MA_HM_THU;
					}
					else
					{
						this._MA_HM_THU = default(int);
					}
					this.SendPropertyChanged("HANG_MUC_THU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_PHIEU_THU", Storage="_TAI_KHOAN", ThisKey="MATK", OtherKey="MATK", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.PHIEU_THUs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.PHIEU_THUs.Add(this);
						this._MATK = value.MATK;
					}
					else
					{
						this._MATK = default(string);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NGUOI_DUNG")]
	public partial class QL_NGUOI_DUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANGUOIDUNG;
		
		private string _MATKHAU;
		
		private System.Nullable<bool> _HOATDONG;
		
		private EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG> _QL_NGUOIDUNG_NHOMNGUOIDUNGs;
		
		private EntitySet<TAI_KHOAN> _TAI_KHOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANGUOIDUNGChanging(string value);
    partial void OnMANGUOIDUNGChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOATDONGChanging(System.Nullable<bool> value);
    partial void OnHOATDONGChanged();
    #endregion
		
		public QL_NGUOI_DUNG()
		{
			this._QL_NGUOIDUNG_NHOMNGUOIDUNGs = new EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG>(new Action<QL_NGUOIDUNG_NHOMNGUOIDUNG>(this.attach_QL_NGUOIDUNG_NHOMNGUOIDUNGs), new Action<QL_NGUOIDUNG_NHOMNGUOIDUNG>(this.detach_QL_NGUOIDUNG_NHOMNGUOIDUNGs));
			this._TAI_KHOANs = new EntitySet<TAI_KHOAN>(new Action<TAI_KHOAN>(this.attach_TAI_KHOANs), new Action<TAI_KHOAN>(this.detach_TAI_KHOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANGUOIDUNG
		{
			get
			{
				return this._MANGUOIDUNG;
			}
			set
			{
				if ((this._MANGUOIDUNG != value))
				{
					this.OnMANGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANGUOIDUNG = value;
					this.SendPropertyChanged("MANGUOIDUNG");
					this.OnMANGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(15)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOATDONG", DbType="Bit")]
		public System.Nullable<bool> HOATDONG
		{
			get
			{
				return this._HOATDONG;
			}
			set
			{
				if ((this._HOATDONG != value))
				{
					this.OnHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._HOATDONG = value;
					this.SendPropertyChanged("HOATDONG");
					this.OnHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NGUOI_DUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG", Storage="_QL_NGUOIDUNG_NHOMNGUOIDUNGs", ThisKey="MANGUOIDUNG", OtherKey="MANGUOIDUNG")]
		public EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG> QL_NGUOIDUNG_NHOMNGUOIDUNGs
		{
			get
			{
				return this._QL_NGUOIDUNG_NHOMNGUOIDUNGs;
			}
			set
			{
				this._QL_NGUOIDUNG_NHOMNGUOIDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NGUOI_DUNG_TAI_KHOAN", Storage="_TAI_KHOANs", ThisKey="MANGUOIDUNG", OtherKey="MANGUOIDUNG")]
		public EntitySet<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this._TAI_KHOANs;
			}
			set
			{
				this._TAI_KHOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_NGUOIDUNG_NHOMNGUOIDUNGs(QL_NGUOIDUNG_NHOMNGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.QL_NGUOI_DUNG = this;
		}
		
		private void detach_QL_NGUOIDUNG_NHOMNGUOIDUNGs(QL_NGUOIDUNG_NHOMNGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.QL_NGUOI_DUNG = null;
		}
		
		private void attach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.QL_NGUOI_DUNG = this;
		}
		
		private void detach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.QL_NGUOI_DUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NGUOIDUNG_NHOMNGUOIDUNG")]
	public partial class QL_NGUOIDUNG_NHOMNGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_NHOM;
		
		private string _MANGUOIDUNG;
		
		private string _CHI_TIET;
		
		private EntityRef<QL_NGUOI_DUNG> _QL_NGUOI_DUNG;
		
		private EntityRef<QL_NHOM_ND> _QL_NHOM_ND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_NHOMChanging(string value);
    partial void OnMA_NHOMChanged();
    partial void OnMANGUOIDUNGChanging(string value);
    partial void OnMANGUOIDUNGChanged();
    partial void OnCHI_TIETChanging(string value);
    partial void OnCHI_TIETChanged();
    #endregion
		
		public QL_NGUOIDUNG_NHOMNGUOIDUNG()
		{
			this._QL_NGUOI_DUNG = default(EntityRef<QL_NGUOI_DUNG>);
			this._QL_NHOM_ND = default(EntityRef<QL_NHOM_ND>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHOM", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_NHOM
		{
			get
			{
				return this._MA_NHOM;
			}
			set
			{
				if ((this._MA_NHOM != value))
				{
					if (this._QL_NHOM_ND.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NHOMChanging(value);
					this.SendPropertyChanging();
					this._MA_NHOM = value;
					this.SendPropertyChanged("MA_NHOM");
					this.OnMA_NHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANGUOIDUNG
		{
			get
			{
				return this._MANGUOIDUNG;
			}
			set
			{
				if ((this._MANGUOIDUNG != value))
				{
					if (this._QL_NGUOI_DUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANGUOIDUNG = value;
					this.SendPropertyChanged("MANGUOIDUNG");
					this.OnMANGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHI_TIET", DbType="NVarChar(30)")]
		public string CHI_TIET
		{
			get
			{
				return this._CHI_TIET;
			}
			set
			{
				if ((this._CHI_TIET != value))
				{
					this.OnCHI_TIETChanging(value);
					this.SendPropertyChanging();
					this._CHI_TIET = value;
					this.SendPropertyChanged("CHI_TIET");
					this.OnCHI_TIETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NGUOI_DUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG", Storage="_QL_NGUOI_DUNG", ThisKey="MANGUOIDUNG", OtherKey="MANGUOIDUNG", IsForeignKey=true)]
		public QL_NGUOI_DUNG QL_NGUOI_DUNG
		{
			get
			{
				return this._QL_NGUOI_DUNG.Entity;
			}
			set
			{
				QL_NGUOI_DUNG previousValue = this._QL_NGUOI_DUNG.Entity;
				if (((previousValue != value) 
							|| (this._QL_NGUOI_DUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NGUOI_DUNG.Entity = null;
						previousValue.QL_NGUOIDUNG_NHOMNGUOIDUNGs.Remove(this);
					}
					this._QL_NGUOI_DUNG.Entity = value;
					if ((value != null))
					{
						value.QL_NGUOIDUNG_NHOMNGUOIDUNGs.Add(this);
						this._MANGUOIDUNG = value.MANGUOIDUNG;
					}
					else
					{
						this._MANGUOIDUNG = default(string);
					}
					this.SendPropertyChanged("QL_NGUOI_DUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NHOM_ND_QL_NGUOIDUNG_NHOMNGUOIDUNG", Storage="_QL_NHOM_ND", ThisKey="MA_NHOM", OtherKey="MA_NHOM", IsForeignKey=true)]
		public QL_NHOM_ND QL_NHOM_ND
		{
			get
			{
				return this._QL_NHOM_ND.Entity;
			}
			set
			{
				QL_NHOM_ND previousValue = this._QL_NHOM_ND.Entity;
				if (((previousValue != value) 
							|| (this._QL_NHOM_ND.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NHOM_ND.Entity = null;
						previousValue.QL_NGUOIDUNG_NHOMNGUOIDUNGs.Remove(this);
					}
					this._QL_NHOM_ND.Entity = value;
					if ((value != null))
					{
						value.QL_NGUOIDUNG_NHOMNGUOIDUNGs.Add(this);
						this._MA_NHOM = value.MA_NHOM;
					}
					else
					{
						this._MA_NHOM = default(string);
					}
					this.SendPropertyChanged("QL_NHOM_ND");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NHOM_ND")]
	public partial class QL_NHOM_ND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_NHOM;
		
		private string _TEN_NHOM;
		
		private string _CHITIET;
		
		private EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG> _QL_NGUOIDUNG_NHOMNGUOIDUNGs;
		
		private EntitySet<QL_PHANQUYEN> _QL_PHANQUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_NHOMChanging(string value);
    partial void OnMA_NHOMChanged();
    partial void OnTEN_NHOMChanging(string value);
    partial void OnTEN_NHOMChanged();
    partial void OnCHITIETChanging(string value);
    partial void OnCHITIETChanged();
    #endregion
		
		public QL_NHOM_ND()
		{
			this._QL_NGUOIDUNG_NHOMNGUOIDUNGs = new EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG>(new Action<QL_NGUOIDUNG_NHOMNGUOIDUNG>(this.attach_QL_NGUOIDUNG_NHOMNGUOIDUNGs), new Action<QL_NGUOIDUNG_NHOMNGUOIDUNG>(this.detach_QL_NGUOIDUNG_NHOMNGUOIDUNGs));
			this._QL_PHANQUYENs = new EntitySet<QL_PHANQUYEN>(new Action<QL_PHANQUYEN>(this.attach_QL_PHANQUYENs), new Action<QL_PHANQUYEN>(this.detach_QL_PHANQUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHOM", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_NHOM
		{
			get
			{
				return this._MA_NHOM;
			}
			set
			{
				if ((this._MA_NHOM != value))
				{
					this.OnMA_NHOMChanging(value);
					this.SendPropertyChanging();
					this._MA_NHOM = value;
					this.SendPropertyChanged("MA_NHOM");
					this.OnMA_NHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_NHOM", DbType="Char(10)")]
		public string TEN_NHOM
		{
			get
			{
				return this._TEN_NHOM;
			}
			set
			{
				if ((this._TEN_NHOM != value))
				{
					this.OnTEN_NHOMChanging(value);
					this.SendPropertyChanging();
					this._TEN_NHOM = value;
					this.SendPropertyChanged("TEN_NHOM");
					this.OnTEN_NHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET", DbType="NVarChar(30)")]
		public string CHITIET
		{
			get
			{
				return this._CHITIET;
			}
			set
			{
				if ((this._CHITIET != value))
				{
					this.OnCHITIETChanging(value);
					this.SendPropertyChanging();
					this._CHITIET = value;
					this.SendPropertyChanged("CHITIET");
					this.OnCHITIETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NHOM_ND_QL_NGUOIDUNG_NHOMNGUOIDUNG", Storage="_QL_NGUOIDUNG_NHOMNGUOIDUNGs", ThisKey="MA_NHOM", OtherKey="MA_NHOM")]
		public EntitySet<QL_NGUOIDUNG_NHOMNGUOIDUNG> QL_NGUOIDUNG_NHOMNGUOIDUNGs
		{
			get
			{
				return this._QL_NGUOIDUNG_NHOMNGUOIDUNGs;
			}
			set
			{
				this._QL_NGUOIDUNG_NHOMNGUOIDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NHOM_ND_QL_PHANQUYEN", Storage="_QL_PHANQUYENs", ThisKey="MA_NHOM", OtherKey="MA_NHOM")]
		public EntitySet<QL_PHANQUYEN> QL_PHANQUYENs
		{
			get
			{
				return this._QL_PHANQUYENs;
			}
			set
			{
				this._QL_PHANQUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_NGUOIDUNG_NHOMNGUOIDUNGs(QL_NGUOIDUNG_NHOMNGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.QL_NHOM_ND = this;
		}
		
		private void detach_QL_NGUOIDUNG_NHOMNGUOIDUNGs(QL_NGUOIDUNG_NHOMNGUOIDUNG entity)
		{
			this.SendPropertyChanging();
			entity.QL_NHOM_ND = null;
		}
		
		private void attach_QL_PHANQUYENs(QL_PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.QL_NHOM_ND = this;
		}
		
		private void detach_QL_PHANQUYENs(QL_PHANQUYEN entity)
		{
			this.SendPropertyChanging();
			entity.QL_NHOM_ND = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_PHANQUYEN")]
	public partial class QL_PHANQUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_NHOM;
		
		private int _MA_MANHINH;
		
		private System.Nullable<bool> _COQUYEN;
		
		private EntityRef<DM_MANHINH> _DM_MANHINH;
		
		private EntityRef<QL_NHOM_ND> _QL_NHOM_ND;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_NHOMChanging(string value);
    partial void OnMA_NHOMChanged();
    partial void OnMA_MANHINHChanging(int value);
    partial void OnMA_MANHINHChanged();
    partial void OnCOQUYENChanging(System.Nullable<bool> value);
    partial void OnCOQUYENChanged();
    #endregion
		
		public QL_PHANQUYEN()
		{
			this._DM_MANHINH = default(EntityRef<DM_MANHINH>);
			this._QL_NHOM_ND = default(EntityRef<QL_NHOM_ND>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_NHOM", DbType="Char(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_NHOM
		{
			get
			{
				return this._MA_NHOM;
			}
			set
			{
				if ((this._MA_NHOM != value))
				{
					if (this._QL_NHOM_ND.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_NHOMChanging(value);
					this.SendPropertyChanging();
					this._MA_NHOM = value;
					this.SendPropertyChanged("MA_NHOM");
					this.OnMA_NHOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_MANHINH", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MA_MANHINH
		{
			get
			{
				return this._MA_MANHINH;
			}
			set
			{
				if ((this._MA_MANHINH != value))
				{
					if (this._DM_MANHINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_MANHINHChanging(value);
					this.SendPropertyChanging();
					this._MA_MANHINH = value;
					this.SendPropertyChanged("MA_MANHINH");
					this.OnMA_MANHINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COQUYEN", DbType="Bit")]
		public System.Nullable<bool> COQUYEN
		{
			get
			{
				return this._COQUYEN;
			}
			set
			{
				if ((this._COQUYEN != value))
				{
					this.OnCOQUYENChanging(value);
					this.SendPropertyChanging();
					this._COQUYEN = value;
					this.SendPropertyChanged("COQUYEN");
					this.OnCOQUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DM_MANHINH_QL_PHANQUYEN", Storage="_DM_MANHINH", ThisKey="MA_MANHINH", OtherKey="MA_MANHINH", IsForeignKey=true)]
		public DM_MANHINH DM_MANHINH
		{
			get
			{
				return this._DM_MANHINH.Entity;
			}
			set
			{
				DM_MANHINH previousValue = this._DM_MANHINH.Entity;
				if (((previousValue != value) 
							|| (this._DM_MANHINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DM_MANHINH.Entity = null;
						previousValue.QL_PHANQUYENs.Remove(this);
					}
					this._DM_MANHINH.Entity = value;
					if ((value != null))
					{
						value.QL_PHANQUYENs.Add(this);
						this._MA_MANHINH = value.MA_MANHINH;
					}
					else
					{
						this._MA_MANHINH = default(int);
					}
					this.SendPropertyChanged("DM_MANHINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NHOM_ND_QL_PHANQUYEN", Storage="_QL_NHOM_ND", ThisKey="MA_NHOM", OtherKey="MA_NHOM", IsForeignKey=true)]
		public QL_NHOM_ND QL_NHOM_ND
		{
			get
			{
				return this._QL_NHOM_ND.Entity;
			}
			set
			{
				QL_NHOM_ND previousValue = this._QL_NHOM_ND.Entity;
				if (((previousValue != value) 
							|| (this._QL_NHOM_ND.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NHOM_ND.Entity = null;
						previousValue.QL_PHANQUYENs.Remove(this);
					}
					this._QL_NHOM_ND.Entity = value;
					if ((value != null))
					{
						value.QL_PHANQUYENs.Add(this);
						this._MA_NHOM = value.MA_NHOM;
					}
					else
					{
						this._MA_NHOM = default(string);
					}
					this.SendPropertyChanged("QL_NHOM_ND");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAI_KHOAN")]
	public partial class TAI_KHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATK;
		
		private string _MALOAI;
		
		private string _MANGUOIDUNG;
		
		private string _TENTK;
		
		private System.Nullable<decimal> _SODUBD;
		
		private System.Nullable<bool> _TRANGTHAI;
		
		private string _DIENGIAI;
		
		private EntitySet<PHIEU_CHI> _PHIEU_CHIs;
		
		private EntitySet<PHIEU_THU> _PHIEU_THUs;
		
		private EntityRef<QL_NGUOI_DUNG> _QL_NGUOI_DUNG;
		
		private EntityRef<TIEN_TE> _TIEN_TE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKChanging(string value);
    partial void OnMATKChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnMANGUOIDUNGChanging(string value);
    partial void OnMANGUOIDUNGChanged();
    partial void OnTENTKChanging(string value);
    partial void OnTENTKChanged();
    partial void OnSODUBDChanging(System.Nullable<decimal> value);
    partial void OnSODUBDChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<bool> value);
    partial void OnTRANGTHAIChanged();
    partial void OnDIENGIAIChanging(string value);
    partial void OnDIENGIAIChanged();
    #endregion
		
		public TAI_KHOAN()
		{
			this._PHIEU_CHIs = new EntitySet<PHIEU_CHI>(new Action<PHIEU_CHI>(this.attach_PHIEU_CHIs), new Action<PHIEU_CHI>(this.detach_PHIEU_CHIs));
			this._PHIEU_THUs = new EntitySet<PHIEU_THU>(new Action<PHIEU_THU>(this.attach_PHIEU_THUs), new Action<PHIEU_THU>(this.detach_PHIEU_THUs));
			this._QL_NGUOI_DUNG = default(EntityRef<QL_NGUOI_DUNG>);
			this._TIEN_TE = default(EntityRef<TIEN_TE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATK", DbType="Char(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATK
		{
			get
			{
				return this._MATK;
			}
			set
			{
				if ((this._MATK != value))
				{
					this.OnMATKChanging(value);
					this.SendPropertyChanging();
					this._MATK = value;
					this.SendPropertyChanged("MATK");
					this.OnMATKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(5) NOT NULL", CanBeNull=false)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._TIEN_TE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGUOIDUNG", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string MANGUOIDUNG
		{
			get
			{
				return this._MANGUOIDUNG;
			}
			set
			{
				if ((this._MANGUOIDUNG != value))
				{
					if (this._QL_NGUOI_DUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._MANGUOIDUNG = value;
					this.SendPropertyChanged("MANGUOIDUNG");
					this.OnMANGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTK", DbType="NVarChar(50)")]
		public string TENTK
		{
			get
			{
				return this._TENTK;
			}
			set
			{
				if ((this._TENTK != value))
				{
					this.OnTENTKChanging(value);
					this.SendPropertyChanging();
					this._TENTK = value;
					this.SendPropertyChanged("TENTK");
					this.OnTENTKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SODUBD", DbType="Money")]
		public System.Nullable<decimal> SODUBD
		{
			get
			{
				return this._SODUBD;
			}
			set
			{
				if ((this._SODUBD != value))
				{
					this.OnSODUBDChanging(value);
					this.SendPropertyChanging();
					this._SODUBD = value;
					this.SendPropertyChanged("SODUBD");
					this.OnSODUBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="Bit")]
		public System.Nullable<bool> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIENGIAI", DbType="NVarChar(50)")]
		public string DIENGIAI
		{
			get
			{
				return this._DIENGIAI;
			}
			set
			{
				if ((this._DIENGIAI != value))
				{
					this.OnDIENGIAIChanging(value);
					this.SendPropertyChanging();
					this._DIENGIAI = value;
					this.SendPropertyChanged("DIENGIAI");
					this.OnDIENGIAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_PHIEU_CHI", Storage="_PHIEU_CHIs", ThisKey="MATK", OtherKey="MATK")]
		public EntitySet<PHIEU_CHI> PHIEU_CHIs
		{
			get
			{
				return this._PHIEU_CHIs;
			}
			set
			{
				this._PHIEU_CHIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_PHIEU_THU", Storage="_PHIEU_THUs", ThisKey="MATK", OtherKey="MATK")]
		public EntitySet<PHIEU_THU> PHIEU_THUs
		{
			get
			{
				return this._PHIEU_THUs;
			}
			set
			{
				this._PHIEU_THUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NGUOI_DUNG_TAI_KHOAN", Storage="_QL_NGUOI_DUNG", ThisKey="MANGUOIDUNG", OtherKey="MANGUOIDUNG", IsForeignKey=true)]
		public QL_NGUOI_DUNG QL_NGUOI_DUNG
		{
			get
			{
				return this._QL_NGUOI_DUNG.Entity;
			}
			set
			{
				QL_NGUOI_DUNG previousValue = this._QL_NGUOI_DUNG.Entity;
				if (((previousValue != value) 
							|| (this._QL_NGUOI_DUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NGUOI_DUNG.Entity = null;
						previousValue.TAI_KHOANs.Remove(this);
					}
					this._QL_NGUOI_DUNG.Entity = value;
					if ((value != null))
					{
						value.TAI_KHOANs.Add(this);
						this._MANGUOIDUNG = value.MANGUOIDUNG;
					}
					else
					{
						this._MANGUOIDUNG = default(string);
					}
					this.SendPropertyChanged("QL_NGUOI_DUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TIEN_TE_TAI_KHOAN", Storage="_TIEN_TE", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public TIEN_TE TIEN_TE
		{
			get
			{
				return this._TIEN_TE.Entity;
			}
			set
			{
				TIEN_TE previousValue = this._TIEN_TE.Entity;
				if (((previousValue != value) 
							|| (this._TIEN_TE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TIEN_TE.Entity = null;
						previousValue.TAI_KHOANs.Remove(this);
					}
					this._TIEN_TE.Entity = value;
					if ((value != null))
					{
						value.TAI_KHOANs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("TIEN_TE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEU_CHIs(PHIEU_CHI entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_PHIEU_CHIs(PHIEU_CHI entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
		
		private void attach_PHIEU_THUs(PHIEU_THU entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_PHIEU_THUs(PHIEU_THU entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
	}
}
#pragma warning restore 1591
