<?xml version="1.0" encoding="utf-8"?><Database Name="QLTC" Class="LinQtoSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-7GUUUSA\SQLEXPRESS;Initial Catalog=QLTC;User ID=sa" SettingsObjectName="LinQ.Properties.Settings" SettingsPropertyName="QLTCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CT_HANG_MUC_CHI" Member="CT_HANG_MUC_CHIs">
    <Type Name="CT_HANG_MUC_CHI">
      <Column Name="MA_CTHM_CHI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_CTHM_CHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GHI_CHU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MA_HM_CHI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CT_HANG_MUC_CHI_PHIEU_CHI" Member="PHIEU_CHIs" ThisKey="MA_CTHM_CHI" OtherKey="MA_CTHM_CHI" Type="PHIEU_CHI" />
      <Association Name="HANG_MUC_CHI_CT_HANG_MUC_CHI" Member="HANG_MUC_CHI" ThisKey="MA_HM_CHI" OtherKey="MA_HM_CHI" Type="HANG_MUC_CHI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TIEN_TE" Member="TIEN_TEs">
    <Type Name="TIEN_TE">
      <Column Name="MALOAI" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="Char(5)" CanBeNull="true" />
      <Column Name="TI_GIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="TIEN_TE_TAI_KHOAN" Member="TAI_KHOANs" ThisKey="MALOAI" OtherKey="MALOAI" Type="TAI_KHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MA_MANHINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_MANHINH" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MA_MANHINH" OtherKey="MA_MANHINH" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.HANG_MUC_CHI" Member="HANG_MUC_CHIs">
    <Type Name="HANG_MUC_CHI">
      <Column Name="MA_HM_CHI" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_HM_CHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CHUTHICH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="HANG_MUC_CHI_CT_HANG_MUC_CHI" Member="CT_HANG_MUC_CHIs" ThisKey="MA_HM_CHI" OtherKey="MA_HM_CHI" Type="CT_HANG_MUC_CHI" />
    </Type>
  </Table>
  <Table Name="dbo.HANG_MUC_THU" Member="HANG_MUC_THUs">
    <Type Name="HANG_MUC_THU">
      <Column Name="MA_HM_THU" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_HM_THU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="HANG_MUC_THU_PHIEU_THU" Member="PHIEU_THUs" ThisKey="MA_HM_THU" OtherKey="MA_HM_THU" Type="PHIEU_THU" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_CHI" Member="PHIEU_CHIs">
    <Type Name="PHIEU_CHI">
      <Column Name="MA_PCHI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_CTHM_CHI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MATK" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_LAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SO_TIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CHU_THICH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CHI_CHO_AI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CT_HANG_MUC_CHI_PHIEU_CHI" Member="CT_HANG_MUC_CHI" ThisKey="MA_CTHM_CHI" OtherKey="MA_CTHM_CHI" Type="CT_HANG_MUC_CHI" IsForeignKey="true" />
      <Association Name="TAI_KHOAN_PHIEU_CHI" Member="TAI_KHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAI_KHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIEU_THU" Member="PHIEU_THUs">
    <Type Name="PHIEU_THU">
      <Column Name="MAPTHU" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_HM_THU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MATK" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="TIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="THU_TU_AI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HANG_MUC_THU_PHIEU_THU" Member="HANG_MUC_THU" ThisKey="MA_HM_THU" OtherKey="MA_HM_THU" Type="HANG_MUC_THU" IsForeignKey="true" />
      <Association Name="TAI_KHOAN_PHIEU_THU" Member="TAI_KHOAN" ThisKey="MATK" OtherKey="MATK" Type="TAI_KHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOI_DUNG" Member="QL_NGUOI_DUNGs">
    <Type Name="QL_NGUOI_DUNG">
      <Column Name="MANGUOIDUNG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(15)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="QL_NGUOI_DUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="MANGUOIDUNG" OtherKey="MANGUOIDUNG" Type="QL_NGUOIDUNG_NHOMNGUOIDUNG" />
      <Association Name="QL_NGUOI_DUNG_TAI_KHOAN" Member="TAI_KHOANs" ThisKey="MANGUOIDUNG" OtherKey="MANGUOIDUNG" Type="TAI_KHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG_NHOMNGUOIDUNG">
      <Column Name="MA_NHOM" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANGUOIDUNG" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CHI_TIET" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="QL_NGUOI_DUNG_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOI_DUNG" ThisKey="MANGUOIDUNG" OtherKey="MANGUOIDUNG" Type="QL_NGUOI_DUNG" IsForeignKey="true" />
      <Association Name="QL_NHOM_ND_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NHOM_ND" ThisKey="MA_NHOM" OtherKey="MA_NHOM" Type="QL_NHOM_ND" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOM_ND" Member="QL_NHOM_NDs">
    <Type Name="QL_NHOM_ND">
      <Column Name="MA_NHOM" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_NHOM" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="CHITIET" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="QL_NHOM_ND_QL_NGUOIDUNG_NHOMNGUOIDUNG" Member="QL_NGUOIDUNG_NHOMNGUOIDUNGs" ThisKey="MA_NHOM" OtherKey="MA_NHOM" Type="QL_NGUOIDUNG_NHOMNGUOIDUNG" />
      <Association Name="QL_NHOM_ND_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MA_NHOM" OtherKey="MA_NHOM" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="MA_NHOM" Type="System.String" DbType="Char(2) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_MANHINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="DM_MANHINH" ThisKey="MA_MANHINH" OtherKey="MA_MANHINH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOM_ND_QL_PHANQUYEN" Member="QL_NHOM_ND" ThisKey="MA_NHOM" OtherKey="MA_NHOM" Type="QL_NHOM_ND" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAI_KHOAN" Member="TAI_KHOANs">
    <Type Name="TAI_KHOAN">
      <Column Name="MATK" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="MANGUOIDUNG" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="TENTK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SODUBD" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DIENGIAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TAI_KHOAN_PHIEU_CHI" Member="PHIEU_CHIs" ThisKey="MATK" OtherKey="MATK" Type="PHIEU_CHI" />
      <Association Name="TAI_KHOAN_PHIEU_THU" Member="PHIEU_THUs" ThisKey="MATK" OtherKey="MATK" Type="PHIEU_THU" />
      <Association Name="QL_NGUOI_DUNG_TAI_KHOAN" Member="QL_NGUOI_DUNG" ThisKey="MANGUOIDUNG" OtherKey="MANGUOIDUNG" Type="QL_NGUOI_DUNG" IsForeignKey="true" />
      <Association Name="TIEN_TE_TAI_KHOAN" Member="TIEN_TE" ThisKey="MALOAI" OtherKey="MALOAI" Type="TIEN_TE" IsForeignKey="true" />
    </Type>
  </Table>
</Database>